
export const DEFAULT_BLOCK_EXPLORER_URLS: { [chainId: string]: string } = {
  '1': 'https://api.etherscan.io',
  '3': 'https://api-ropsten.etherscan.io',
  '4': 'https://api-rinkeby.etherscan.io',
  '5': 'https://api-goerli.etherscan.io',
  '10': 'https://api-optimistic.etherscan.io',
  '42': 'https://api-kovan.etherscan.io',
  '97': 'https://api-testnet.bscscan.com',
  '56': 'https://api.bscscan.com',
  '69': 'https://api-kovan-optimistic.etherscan.io',
  '70': 'https://api.hooscan.com',
  '77': 'https://blockscout.com/poa/sokol',
  '128': 'https://api.hecoinfo.com',
  '137': 'https://api.polygonscan.com',
  '250': 'https://api.ftmscan.com',
  '256': 'https://api-testnet.hecoinfo.com',
  '420': 'https://api-goerli-optimism.etherscan.io',
  '588': 'https://stardust-explorer.metis.io',
  '1088': 'https://andromeda-explorer.metis.io',
  '1285': 'https://api-moonriver.moonscan.io',
  '80001': 'https://api-testnet.polygonscan.com',
  '4002': 'https://api-testnet.ftmscan.com',
  '42161': 'https://api.arbiscan.io',
  '421611': 'https://api-testnet.arbiscan.io',
  '421613': 'https://api-goerli.arbiscan.io',
  '43113': 'https://api-testnet.snowtrace.io',
  '43114': 'https://api.snowtrace.io',
  '11155111': 'https://api-sepolia.etherscan.io',
};
